In [1]:
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [2]:
env = GridworldEnv()

In [118]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a (prob, next_state, reward, done) tuple.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    V1 = np.zeros(env.nS)
    # print (V.shape)
    
    # print ('policy:', policy)
    # print (env.P[0][0][0][0])
    # print (env.P.dtype)
    # print(policy.shape)
    
    counter = 0
    while True:
        counter += 1
        print(counter)
        V1 = np.zeros(env.nS)
        for s, value in enumerate(V):
            for a in range(env.nA):
                reward = env.P[s][a][0][2]
                prob = env.P[s][a][0][0]
                next_state = env.P[s][a][0][1]
                V1[s] += policy[s][a] * (reward + discount_factor * prob * V[next_state]) 
        
        print('V1:', V1.reshape(env.shape))
        print('V: ', V.reshape(env.shape))
        print(np.abs(V1-V).reshape(env.shape))
        # print(np.abs(V1-V).reshape(env.shape))
        delta = np.abs(V1 - V)
        if np.all(delta < theta):
            print('exiting...', theta)
            break
        V = np.copy(V1)
    return np.array(V)

In [119]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

1
V1: [[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
V:  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  0.]]
2
V1: [[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
V:  [[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0.    0.75  1.    1.  ]
 [ 0.75  1.    1.    1.  ]
 [ 1.    1.    1.    0.75]
 [ 1.    1.    0.75  0.  ]]
3
V1: [[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
V:  [[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
[[ 0.      0.6875  0.9375  1.    ]
 [ 0.6875  0.875   1.      0.9375]
 [ 0.9375  1.      0.875   0.6875]
 [ 1.      0.9375  0.6875  0.    ]]
4
V1: [[ 0.      -3.0625  -3.84375 -3.96875]
 [-3.062

In [122]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)